<html>
	<script type="text/javascript" src="/js/jquery.js"></script>
	<head>
		<meta charset="UTF-8">
		<title>Register</title>

		<link rel="stylesheet" href="/stylesheets/style.css">
		<script type="text/javascript" src="/js/jquery.js"></script>

	</head>
	<body>
		<div class="wrapper">
			<div class="container">
				<h1>Welcome</h1>

				<form class="form" action="/user/register" method="post">
					<input type="text" placeholder="Username" name="username" class="inp" id="username">
					<span
						style="color: green; position: absolute; margin-top: -9%; margin-left: 25%; font-size: 150%"
						id="user"></span>
					<input type="password" placeholder="Password" name="password" class="inp">
					<input type="text" placeholder="Place" name="place" class="inp">
					<input type="text" placeholder="about" name="about" class="inp">
					<button type="submit" id="login-button" class="inp">Register</button>
				</form>
			</div>

			<ul class="bg-bubbles">
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
				<li></li>
			</ul>
		</div>
		<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>


		<script type="text/javascript">
			$("#username").keyup(function (e) { //user types username on inputfiled
				var username = $(this).val(); //get the string typed by user

				jQuery.ajax({
					url: "/user/unique/username/" + username,
					type: "GET",
					complete: function (res, status) {
						if (status === "success") {

							var resarray = jQuery.parseJSON(res.responseText);
							if (resarray.status) {
								var new_state = resarray.data;
								if (!resarray.error) {
									if(new_state == true) {
										document.getElementById("user").innerHTML = "Valid Username";
										document.getElementById("user").style.color = "green";
									}
									else {
										document.getElementById("user").innerHTML = "Invalid Username";
										document.getElementById("user").style.color = "red";
									}
								}
							} else {
							}
						}
						else {

						}
					}
				});

			});
		</script>

	</body>
</html>