<head>
	<title>Edit profile</title>
	<link rel="stylesheet" href="/stylesheets/form.css" />
</head>
<div class="form-style-5">
	<form method="post" action="/post/new" enctype="multipart/form-data" >
		<fieldset>
			<legend><span class="number">1</span> New Post</legend>
			Post content:<br><br><textarea name="content" cols="30" rows="10"></textarea>
			Pic:
			<input name="post_pic" type="file" />
			<br><br>
		</fieldset>
		<input type="submit" value="Apply" />
	</form>
</div>